export const LOGIN_PAGE = '/pages/login/login'
export const REGISTER_PAGE = '/pages/register/register'
export const USER_PAGE = '/pages/user/user'
export const INDEX_PAGE = '/pages/index/index'
export const SUBSCRIBE_PAGE = '/pages/subscribe/subscribe'
export const MANGA_PAGE = '/pages/manga/manga'
export const BROWSE_PAGE = '/pages/browse/browse'
